### ISSUE TITLE
Dodanie serwisów obsługujących API

### ISSUE THREAD

**Issue by kanapka94** [SGGW-mgr-2018/KorepetycjeNaJuz-Front#11]
- [x] wyciągnięcie od backendu linków do API
- [x] dodanie axiosa
- [x] dodanie podstawowych serwisów na stronę

**Comment by magdasid** [comment]
Narazie nic, na dniach zacznie się coś pojawiać wraz z opisami ;)

**Comment by kanapka94** [comment]
Oki dzięki :)
