### ISSUE TITLE
Dodanie sekcji - Korepetycje nie nigdy nie były prostsze

### ISSUE THREAD

**Issue by kanapka94** [SGGW-mgr-2018/KorepetycjeNaJuz-Front#27]
Stworzyłem dla Ciebie komponent Description w @/components/Home/Description

**Comment by Leivin** [comment]
RWD: Zmniejszenie marginesów bocznych na rozdzielczościach mobilnych (a najlepiej zamiana ich na paddingi), zwiększenie odstępu od nagłówka
