### ISSUE TITLE
Stworzenie formularza z logowaniem

### ISSUE THREAD

**Issue by kanapka94** [SGGW-mgr-2018/KorepetycjeNaJuz-Front#34]
Tak naprawdę to jest stworzenie całej tej strony (bez stopki oczywiście, bo ona i header będą zrobione)

**Comment by Leivin** [comment]
Poprawki:
#51

**Comment by magdasid** [comment]
+ sekcja logowania styka się bezpośrednio ze stopką, tam powinien być jakiś większy odstęp.
