### ISSUE TITLE
Dodanie komponentu Zapisz się na Lekcje

### ISSUE THREAD

**Issue by kanapka94** [SGGW-mgr-2018/KorepetycjeNaJuz-Front#54]
https://app.zeplin.io/project/5bdb6f4f6d78130a55505a27/screen/5bfb034e4f961c3f22c9b794

**Comment by magdasid** [comment]
1. Tekst opisu lekcji jest zbyt mały + opis jest chyba teraz na sztywno,
2. Brak daty lekcji, mamy tylko godzinę,
3. Przy kliknięciu na "Zapisz się na lekcje" brak jakiegoś potwierdzenia, od razu nas na nią zapisuje.
