### ISSUE TITLE
Podpięcie wyszukiwania korepetycji pod backend

### ISSUE THREAD

**Issue by kanapka94** [SGGW-mgr-2018/KorepetycjeNaJuz-Front#78]
Wzorujcie się na pliku service.js oraz auth.js (ten jest w Storze)

**Comment by Leivin** [comment]
![image](https://user-images.githubusercontent.com/17150945/50740075-9d8fa600-11e9-11e9-97a0-03ae3276b160.png)

1. Zamiast "Wpisz przedmiot" powinien znajdować się select z możliwością wyboru przedmiotu (pobranych z bazy)
2. Przyciski ucz się teraz/chcę wybrać datę są niepotrzebne - domyślnie wyszukiwanie jest 24h do przodu, w pozostałych przypadkach można wybrać datę.
